baseurl: "https://pgbh2021.pages.dev"
title: "Pangenomics Bio Hacking 2021"
canonifyurls: true
theme: "pgbh-conference"

GoogleAnalytics: ""
GoogleMapsKey: ""

params:
  # Conference info
  Name: "Pangenomics Bio Hacking 2021"
  Description: "Conference description"
  Date: "December 9-10, 2021"
  #  Price: "Only $100" # If your event is free, just comment this line
  Venue: "Aula Sironi"
  Address: "U4 Building, Piazza della Scienza"
  City:  "Milano"
  State: "Italy"
  Images: ["/img/badge.jpg"]
  Github: "https://github.com/gdv/pgbh2021/tree/main/themes/pgbh-conference"
  Registration: "https://docs.google.com/forms/d/e/1FAIpQLSfAdl1X-I_ndYHo9hHmH44VqEf0jiKofI9ZDmraJShzIuMHMQ/viewform"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - speakers
    - schedule
    - sponsors
    - partners
    - story
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    speakers: "Speakers"
    schedule: "Schedule"
    sponsors: "Sponsors"
    partners: "Organizers"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now!"
    link: "https://docs.google.com/forms/d/e/1FAIpQLSfAdl1X-I_ndYHo9hHmH44VqEf0jiKofI9ZDmraJShzIuMHMQ/viewform?usp=sf_link"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
    ForkButton:
      repository: "https://github.com/gdv/pgbh2021"

  # List of Sponsors
  Sponsors:
    - name: "PANGAIA"
      logo: "/img/pangaia-logo-trimmed.png"
      url: "https://pangenome.eu"

    - name: "UNIMIB"
      logo: "/img/LogoIst.jpg"
      url: "https://www.unimib.it"

    - name: "ALPACA"
      logo: "/img/alpaca_logo_title.svg"
      url: "https://alpaca-itn.eu/"


  # List of Partners
  Partners:
    - name: "Enza"
      logo: "/img/vcolonna.jpg"
      url: "https://colonnalab.github.io/laboratory_WebPage/"
    - name: "Gianluca"
      logo: "/img/gianluca.png"
      url: "https://gianluca.dellavedova.org"
    - name: "Erik"
      logo: "/img/erik_garrison_photo.jpg"
      url: "https://www.hypervolu.me/~erik/erik_garrison.html"
    - name: "Pjotr"
      logo: "/img/pjotrprins.jpg"
      url: "https://thebird.nl/"
  
  ############################################    
  # The entire schedule
  ############################################    
  Schedule:
    - name: "Check-in "
      time: "Dec 09 - 9h00"

  ############################################    
  # Day 1 - December 09
  ############################################    
        
    - name: "Shilpa Garg"
      company: "University of Copenhagen"
      link:
        href: "https://www1.bio.ku.dk/english/staff/?pure=en/persons/708474"
        text: "home page"
      presentation:
        title: "Title"
        description: "Short abstract"
        time: "9h30"

    - name: "Hackathon"
      goal: "Hack Goal"
      time: "10h00"

    - name: "Lunch"
      time: "12h00"


    - name: "Hackathon"
      goal: "Hack Goal"
      time: "13h00"

    - name: "Rayan Chikhi"
      company: "Institut Pasteur and CNRS"
      link:
        href: "https://rayan.chikhi.name"
        text: "homepage"
      presentation:
        title: "Representing 661,405 bacterial genomes using minimizer-space de
        Bruijn graphs"
        description: "DNA sequencing continues to progress toward longer and
        more accurate reads. Yet, primary analyses, such as genome assembly and
        pangenome graph construction, remain challenging and energy-inefficient.
        We recently introduced the concept of minimizer-space sequencing
        analysis, expanding the alphabet of DNA sequences to atomic tokens made
        of fixed-length words. This leads to orders-of-magnitude improvements in
        speed and memory usage for human genome assembly and metagenome assembly
        and enables for the first time a representation of a pangenome made of 661,405 bacterial genomes."
        time: "15h00"

    - name: "Danang Crysnanto"
      company: "ETH Zurich"
      link:
          href: "https://github.com/danangcrysnanto"
          text: "website"
      presentation:
          title: "Establishing Bovine Pangenome Graphs"
          description: "The reference genome is generated from a single or few
          individuals and thus, it is a poor representation of the full species
          diversity. This pitfall has led to the development of the pangenome;
          the use of multiple genomes for genomic analysis. In this study, we
          integrated six cattle reference-quality genome assemblies into a
          pangenome graph, and we found 70 Mb sequences are not included in the
          existing cattle reference genome. We further demonstrated that these
          non-reference sequences contain functionally active bases and
          thousands of polymorphic sites that remain undetected with a single
          linear genome. Our findings call the need for a more representative
          reference genome that captures the entire species diversity."
          time: "15h30"

    - name: "Jouni Siren"
      company: "UC Santa Cruz"
      link:
        href: "https://iki.fi/jouni.siren/"
        text: "home page"
      presentation:
        title: "Giraffe: A Pangenomic Short Read Aligner"
        description: "Pangenomic aligners try to avoid reference bias in read mapping by including common variants in the reference. They achieve a higher mapping accuracy than traditional linear aligners, at the expense of being an order of magnitude slower. We present Giraffe, a new short read aligner that avoids this trade-off with a number of algorithmic and data model improvements. By combining the speed of linear aligners with the accuracy of pangenomic aligners, Giraffe is a viable choice for large-scale sequencing projects."
        time: "16h00"

    - name: "Barış Ekim"
      company: "affiliation"
      link:
        href: ""
        text: ""
      presentation:
        title: "Title"
        description: "Short abstract"
        time: "16h30"

    - name: "Christian Kubica"
      company: "Max Planck Institute for Developmental Biology, Tuebingen, Germany"
      link:
        href: "https://github.com/MoinSebi/gSV"
        text: "Github"
      presentation:
        title: "gSV - a reference free SV caller"
        description: "While reference guided variant detection has helped us to explore a large fraction of, mostly non-complex, variation, its properties derived from pairwise comparisons have hindered true pan-genomic analysis. Until now, variant calls have always been reference biased and dependent on sequence being available in the singular reference genome. The coordinate system used has been reference based and thus the sequence context in the query sequence has been lost. Furthermore, nested variation has been hard to access from such variant calls.  By using the information stored in whole genome alignment derived genome graphs we are now able to explore variation in a true pan-genomic environment. Here we present gSV, a first solution to call complex and nested variation as it is represented in a genome graph. gSV explores the graph inherent bubble structures from a fully pan-genomic point of view, thus removing the need for a reference coordinate system. This enables us to access nested variation and assign hierarchical parent-child relationships to bubbles while preserving the sequence context of each variant in every genome."
        time: "17h00"


    - name: "End of Day 1"
      time: "17h30"


  ############################################    
  # Day 2 - December 10
  ############################################    


    - name: "Beginning of Day 2"
      time: "Dec 10 - 9h00"

    - name: "Yan Gao"
      company: "Children's Hospital of Philadelphia and Sun Yat-sen University"
      link:
        href: "https://github.com/yangao07"
        text: "Github"
      presentation:
        title: "Fast and memory-efficient partial order alignment with abPOA"
        description: "We present abPOA (adaptive banded Partial Order Alignment), a Single Instruction Multiple Data (SIMD)-based C library for fast and memory-efficient partial order alignment. abPOA uses a minimizer-based seeding and partition approach to split sequence and graph into small windows and separately performs partial order alignment within each window"
        time: "9h30"

    - name: "Hackathon"
      goal: "Hack Goal"
      time: "10h00"

    - name: "Lunch"
      time: "12h00"


    - name: "Hackathon"
      goal: "Hack Goal"
      time: "13h00"

    - name: "Jana Ebler"
      company: "Heinrich Heine University Düsseldorf"
      link:
        href: "https://bitbucket.org/jana_ebler/pangenie"
        text: "website"
      presentation:
        title: "PanGenie - Pangenome-based inference"
        description: "Typical analysis workflows map reads to a reference genome in order to genotype genetic variants. Generating such alignments introduces reference biases and comes with substantial computational burden. In contrast, recent k-mer based genotypers are fast, but struggle in repetitive or duplicated genomic regions. In this talk, I propose a novel algorithm, PanGenie, that leverages a haplotype-resolved pangenome reference in conjunction with k-mer counts from short-read sequencing data to genotype a wide spectrum of genetic variation - a process we refer to as genome inference. Compared to mapping-based approaches, PanGenie is more than 4x faster at 30x coverage and reaches significantly better genotype concordances for almost all variant types and coverages tested. Improvements are especially pronounced for large insertions (>=50bp) and variants in repetitive regions, enabling the inclusion of these classes of variants in genome-wide association studies. PanGenie efficiently leverages the increasing amount of haplotype-resolved assemblies to unravel the functional impact of previously inaccessible variants while being scalable to thousands of genotyped samples."
        time: "16h00"

    - name: "Flavia Villani"
      company: "University of Tennessee"
      link:
        href: "https://cghs1.uthsc.edu/exist/apps/FacultyCommittees/index.html?range=U-W&tabSelected=committees&netID=fvillan1&surname=Villani&forename=Flavia"
        text: "website"
      presentation:
        title: "A pangenome for the expanded BXD family of mice"
        description: "The members of BXDs family have been inbred for 20-200
        generations . They are of great value for mapping complex traits and
        phenome-wide association analysis. Current genomic studies on BXD assume
        a single linear reference genome, making it difficult to observe
        sequences diverging from the reference, therefore limiting the accuracy
        and completeness of analyses. We sequenced all extant members of all BXD
        families using linked-read libraries and built the pangenome graph to
        study genetic variation. We determined that linked reads are not ideal
        for pangenome building, nevertheless the pangenome enhanced the calling
        of complex variants not seen by traditional genomics methods and
        provided calls with good precision and sensitivity. As a case study we
        followed up a strain specific 2kb insertion that was inherited by half
        of the recombinant mice and correlated the genotype at this locus with
        clinically relevant phenotypes present in the GeneNetwork database."
        time: "16h30"

    - name: "Massimiliano Rossi"
      company: "University of Florida"
      link:
        href: "https://maxrossi91.com"
        text: "home page"
      presentation:
        title: "MONI: Design Challenges for a Pangenomic Tool"
        description: "MONI is a pangenomic index for finding maximal exact matches (MEMs), that is built on top of the r-index but also includes auxiliary data structures to allow finding approximate matches on a pangenomic scale. It includes many open-source tools and data structures such as BigBWT, BigRePair, and SDSL. I will talk about MONI, which is written in C++ and freely available at https://github.com/maxrossi91/moni"
        time: "17h00"


    - name: "Discussion and Greetings"
      time: "17h30"

