baseurl: "https://pgbh2021.pages.dev"
title: "Pangenomics Bio Hacking 2021"
canonifyurls: true
theme: "pgbh-conference"

GoogleAnalytics: ""
GoogleMapsKey: ""

params:
  # Conference info
  Name: "Pangenomics Bio Hacking 2021"
  Description: "Conference description"
  Date: "December 9-10, 2021"
  #  Price: "Only $100" # If your event is free, just comment this line
  Venue: "Aula Sironi"
  Address: "U4 Building, Piazza della Scienza"
  City:  "Milano"
  State: "Italy"
  Images: ["/img/badge.jpg"]
  Github: "https://github.com/gdv/pgbh2021/tree/main/themes/pgbh-conference"
  Registration: "https://docs.google.com/forms/d/e/1FAIpQLSfAdl1X-I_ndYHo9hHmH44VqEf0jiKofI9ZDmraJShzIuMHMQ/viewform"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - speakers
    - schedule
    - sponsors
    - partners
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    speakers: "Speakers"
    schedule: "Schedule"
    sponsors: "Sponsors"
    partners: "Organizers"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now!"
    link: "https://register.example.com"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
    ForkButton:
      repository: "https://github.com/gdv/pgbh2021"

  # List of Sponsors
  Sponsors:
    - name: "PANGAIA"
      logo: "/img/pangaia-logo-trimmed.png"
      url: "https://pangenome.eu"

    - name: "UNIMIB"
      logo: "/img/LogoIst.jpg"
      url: "https://www.unimib.it"

  # List of Partners
  Partners:
    - name: "Enza"
      logo: "/img/hugo.jpg"
      url: "https://colonnalab.github.io/laboratory_WebPage/"
    - name: "Gianluca"
      logo: "/img/gianluca.png"
      url: "https://gianluca.dellavedova.org"
    - name: "Erik"
      logo: "/img/partner.png"
      url: "https://www.hypervolu.me/~erik/erik_garrison.html"
    - name: "Pjotr"
      logo: "/img/pjotrprins.jpg"
      url: "https://thebird.nl/"
  # The entire schedule
  Schedule:
    - name: "Check-in "
      time: "Dec 09 - 9h00"

    - name: "Shilpa Garg"
      photo: "/img/speaker.jpg"
      company: "University of Copenhagen"
      link:
        href: "https://www1.bio.ku.dk/english/staff/?pure=en/persons/708474"
        text: "home page"
      presentation:
        title: "Title"
        description: "Short abstract"
        time: "9h30"

    - name: "Hackathon"
      presentation:
        title: "Hacking time"
        description: "Hackathon focus"
      time: "10h00"

    - name: "Lunch"
      time: "12h00"


    - name: "Hackathon"
      presentation:
        title: "Hacking time"
        description: "Hackathon focus"
      time: "13h00"

    - name: "Jouni Siren"
      photo: "/img/speaker.jpg"
      company: "affiliation"
      link:
        href: "https://github.com/"
        text: "@littlechuck"
      presentation:
        title: "Title"
        description: "Short abstract"
        time: "16h00"

    - name: "???????"
      photo: "/img/speaker.jpg"
      company: "affiliation"
      link:
        href: "https://github.com/"
        text: "@stevie"
      presentation:
        title: "Presenting iPad"
        description: "Lorem ipsum"
        time: "16h20"

    - name: "Barış Ekim"
      photo: "/img/speaker.jpg"
      company: "affiliation"
      link:
        href: "https://github.com/"
        text: "@littlechuck"
      presentation:
        title: "Title"
        description: "Short abstract"
        time: "16h40"

    - name: "Christian Kubica"
      photo: "/img/speaker.jpg"
      company: "affiliation"
      link:
        href: "https://github.com/"
        text: "@zuck"
      presentation:
        title: "Title"
        description: "Short abstract"
        time: "17h00"


    - name: "End of Day 1"
      time: "17h20"






    - name: "Beginning of Day 2"
      time: "Dec 10 - 9h00"

    - name: "Yan Gao"
      photo: "/img/speaker.jpg"
      company: "Children's Hospital of Philadelphia and Sun Yat-sen University"
      link:
        href: "https://github.com/yangao07"
        text: "Github"
      presentation:
        title: "Fast and memory-efficient partial order alignment with abPOA"
        description: "We present abPOA (adaptive banded Partial Order Alignment), a Single Instruction Multiple Data (SIMD)-based C library for fast and memory-efficient partial order alignment. abPOA uses a minimizer-based seeding and partition approach to split sequence and graph into small windows and separately performs partial order alignment within each window"
        time: "9h30"

    - name: "Hackathon"
      presentation:
        title: "Hacking time"
        description: "Hackathon focus"
        time: "10h00"

    - name: "Lunch"
      time: "12h00"


    - name: "Hackathon"
      presentation:
        title: "Hacking time"
        description: "Hackathon focus"
      time: "13h00"

    - name: "Jana Ebler"
      photo: "/img/speaker.jpg"
      company: "affiliation"
      link:
        href: "https://github.com/"
        text: "@littlechuck"
      presentation:
        title: "Title"
        description: "Short abstract"
        time: "16h00"

    - name: "Rayan Chikhi"
      photo: "/img/speaker.jpg"
      company: "Institut Pasteur"
      link:
        href: "https://github.com/stevie"
        text: "@stevie"
      presentation:
        title: "Title"
        description: "Short abstract"
        time: "16h20"

    - name: "Flavia Villani"
      photo: "/img/speaker.jpg"
      company: "affiliation"
      link:
        href: "https://github.com/"
        text: "@littlechuck"
      presentation:
        title: "Title"
        description: "Short abstract"
        time: "16h40"

    - name: "Massimiliano Rossi"
      photo: "/img/speaker.jpg"
      company: "Computer & Information Science & Engineering Department Herbert Wertheim
College of Engineering, University of Florida"
      link:
        href: "https://maxrossi91.com"
        text: "@zuck"
      presentation:
        title: "MONI: Design Challenges for a Pangenomic Tool"
        description: "MONI is a pangenomic index for finding maximal exact matches (MEMs), that is built on top of the r-index but also includes auxiliary data structures to
allow finding approximate matches on a pangenomic scale. It includes many
open-source tools and data structures such as BigBWT, BigRePair, and SDSL. I
will talk about MONI, which is written in C++ and freely available at https://
github.com/maxrossi91/moni"
        time: "17h00"


    - name: "Discussion and Greetings"
      time: "17h20"

