baseurl: "https://pgbh2021.pages.dev"
title: "Pangenomics Bio Hacking 2021"
canonifyurls: true
theme: "pgbh-conference"

GoogleAnalytics: ""
GoogleMapsKey: ""

params:
  # Conference info
  Name: "Pangenomics Bio Hacking 2021"
  Description: "Conference description"
  Date: "December 9-10, 2021"
  #  Price: "Only $100" # If your event is free, just comment this line
  Venue: "Aula Sironi"
  Address: "U4 Building, Piazza della Scienza"
  City:  "Milano"
  State: "Italy"
  Images: ["/img/badge.jpg"]

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - location
    - speakers
    - schedule
    - sponsors
    #- contact

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    location: "Location"
    speakers: "Speakers"
    schedule: "Schedule"
    sponsors: "Sponsors"
    partners: "Partners"
    contact: "Contact"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  CallToAction:
    text: "Register now!"
    link: "http://register.example.com"

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #  ForkButton:
  #    repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "PANGAIA"
      logo: "/img/pangaia-logo-trimmed.png"
      url: "https://pangenome.eu"

    - name: "UNIMIB"
      logo: "/img/LogoIst.jpg"
      url: "https://www.unimib.it"

  # List of Partners
  Partners:
    - name: "Hugo"
      logo: "/img/hugo.jpg"
      url: "https://gohugo.io"
    - name: "BrazilJS"
      logo: "/img/partner.png"
      url: "http://braziljs.org"

  # The entire schedule
  Schedule:
    - name: "Check-in "
      time: "Dec 09 - 9h00"

    - name: "Shilpa Garg"
      photo: "/img/speaker.jpg"
      bio: "New computational algorithms for solving fundamental biological problems of genome assembly, haplotyping and structural variants calling"
      company: "University of Copenhagen"
      link:
        href: "https://www1.bio.ku.dk/english/staff/?pure=en/persons/708474"
        text: "home page"
      presentation:
        title: "Title of the tutorial"
        description: "Short abstract"
        time: "9h30"


    - name: "Lunch"
      time: "12h00"


    - name: "Hackathon"
      photo: "/img/speaker.jpg"
      bio: "Hacking focus?"
      time: "13h00"

    - name: "Jouni Siren"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Delta Command"
      link:
        href: "http://twitter.com/littlechuck"
        text: "@littlechuck"
      presentation:
        title: "How to kill a elephant with one finger"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "16h00"

    - name: "???????"
      photo: "/img/speaker.jpg"
      bio: "Probably somebody more focused on biology"
      company: "Apple, Inc."
      link:
        href: "http://github.com/stevie"
        text: "@stevie"
      presentation:
        title: "Presenting iPad"
        description: "Lorem ipsum"
        time: "16h20"

    - name: "Barış Ekim"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Delta Command"
      link:
        href: "http://twitter.com/littlechuck"
        text: "@littlechuck"
      presentation:
        title: "How to kill a elephant with one finger"
        description: "Lorem ipsum"
        time: "16h40"

    - name: "Christian Kubica"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Facebook"
      link:
        href: "http://twitter.com/zuck"
        text: "@zuck"
      presentation:
        title: "Revealing Facebook Secrets"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "17h00"


    - name: "End of Day 1"
      time: "17h20"

    - name: "Beginning of Day 2"
      time: "Dec 09 - 9h00"

    - name: "Yan Gao"
      photo: "/img/speaker.jpg"
      bio: "New computational algorithms for solving fundamental biological problems of genome assembly, haplotyping and structural variants calling"
      company: "University of Copenhagen"
      link:
        href: "https://www1.bio.ku.dk/english/staff/?pure=en/persons/708474"
        text: "home page"
      presentation:
        title: "Title of the tutorial"
        description: "Short abstract"
        time: "9h30"


    - name: "Lunch"
      time: "12h00"


    - name: "Hackathon"
      photo: "/img/speaker.jpg"
      bio: "Hacking focus?"
      time: "13h00"

    - name: "Jana Ebler"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Delta Command"
      link:
        href: "http://twitter.com/littlechuck"
        text: "@littlechuck"
      presentation:
        title: "How to kill a elephant with one finger"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "16h00"

    - name: "Rayan Chikhi"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Apple, Inc."
      link:
        href: "http://github.com/stevie"
        text: "@stevie"
      presentation:
        title: "Presenting iPad"
        description: "Lorem ipsum"
        time: "16h20"

    - name: "Flavia Villani"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Delta Command"
      link:
        href: "http://twitter.com/littlechuck"
        text: "@littlechuck"
      presentation:
        title: "How to kill a elephant with one finger"
        description: "Lorem ipsum"
        time: "16h40"

    - name: "Massimiliano Rossi"
      photo: "/img/speaker.jpg"
      bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "Facebook"
      link:
        href: "http://twitter.com/zuck"
        text: "@zuck"
      presentation:
        title: "Revealing Facebook Secrets"
        description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
        time: "17h00"


    - name: "Discussion and Greetings"
      time: "17h20"

